### ISSUE TITLE
example ends with error message

### ISSUE THREAD

**Issue by AdrianTschannen** [eloquentarduino/EloquentMicroML#2]
I tried to run the tasks in "The Ultimate Guide to Wifi..", but ended up with the following message when I came to the most interesting part of it (Generating the features converter):

C:\Users\adria\AppData\Local\Programs\Python\Python37-32\python.exe C:/Users/adria/PycharmProjects/IoT_localization/ArduinoLocalization.py
Traceback (most recent call last):
  File "C:/Users/adria/PycharmProjects/IoT_localization/ArduinoLocalization.py", line 10, in <module>
    x, y, classmap, converter_code = port_wifi_indoor_positioning(samples)
  File "C:\Users\adria\AppData\Local\Programs\Python\Python37-32\lib\site-packages\micromlgen\wifiindoorpositioning.py", line 68, in port_wifi_indoor_positioning
    'networkmap': networkmap
  File "C:\Users\adria\AppData\Local\Programs\Python\Python37-32\lib\site-packages\micromlgen\utils.py", line 49, in jinja
    template = Environment(loader=loader).get_template(template_file)
  File "C:\Users\adria\AppData\Local\Programs\Python\Python37-32\lib\site-packages\jinja2\environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "C:\Users\adria\AppData\Local\Programs\Python\Python37-32\lib\site-packages\jinja2\environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "C:\Users\adria\AppData\Local\Programs\Python\Python37-32\lib\site-packages\jinja2\loaders.py", line 115, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "C:\Users\adria\AppData\Local\Programs\Python\Python37-32\lib\site-packages\jinja2\loaders.py", line 197, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: wifiindoorpositioning/wifiindoorpositioning.jinja

Process finished with exit code 1

most likely, my installation has an issue… Thank you for an idea, what the reason of this problem could be. Best, Adrian

**Comment by eloquentarduino** [comment]
Be sure you have the latest version of `micromlgen` installed (1.1.8).
If still not working, run these commands in the terminal:

```bash
pip uninstall micromlgen
pip install https://github.com/eloquentarduino/micromlgen.git
```

If still not working, please report the contents of the folder

`C:\Users\adria\AppData\Local\Programs\Python\Python37-32\lib\site-packages\micromlgen\templates`

**Comment by AdrianTschannen** [comment]
Thank you! I uninstalled and tried to install using
pip install https://github.com/eloquentarduino/micromlgen.git.

But unfortunately this ends up in an error message:

  ERROR: Cannot unpack file C:\Users\adria\AppData\Local\Temp\pip-unpack-yj1txng0\micromlgen.git (downloaded from C:\Users\
adria\AppData\Local\Temp\pip-req-build-yn6x_etg, content-type: text/html; charset=utf-8); cannot detect archive format
ERROR: Cannot determine archive format of C:\Users\adria\AppData\Local\Temp\pip-req-build-yn6x_etg

Hence, I used "pip install --upgrade micromlgen". This seems to work as I receive the following result:
C:\Users\adria\PycharmProjects\IoT_localization>pip install --upgrade micromlgen
Collecting micromlgen
  Using cached micromlgen-1.1.8.tar.gz (9.3 kB)
Requirement already satisfied, skipping upgrade: jinja2 in c:\users\adria\appdata\local\programs\python\python37-32\lib\sit
e-packages (from micromlgen) (2.11.2)
Requirement already satisfied, skipping upgrade: MarkupSafe>=0.23 in c:\users\adria\appdata\local\programs\python\python37-
32\lib\site-packages (from jinja2->micromlgen) (1.1.1)
Using legacy 'setup.py install' for micromlgen, since package 'wheel' is not installed.
Installing collected packages: micromlgen
    Running setup.py install for micromlgen ... done
Successfully installed micromlgen-1.1.8

But this solves not my issue.

In the folder 
C:\Users\adria\AppData\Local\Programs\Python\Python37-32\lib\site-packages\micromlgen\
there is NO subfolder with the name "templates". Under ....\micromlgen\ there are the following files stored:

C:\Users\adria\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\micromlgen>dir
 Datenträger in Laufwerk C: ist Local Disk
 Volumeseriennummer: 9A14-5B46

 Verzeichnis von C:\Users\adria\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\micromlgen

25.08.2020  20:41    <DIR>          .
25.08.2020  20:41    <DIR>          ..
03.08.2020  20:49               591 decisiontree.py
03.08.2020  20:52               505 gaussiannb.py
03.08.2020  20:56               545 logisticregression.py
03.08.2020  21:26             1'427 micromlgen.py
03.08.2020  21:15               387 pca.py
03.08.2020  21:26               262 platforms.py
03.08.2020  20:50               691 randomforest.py
03.08.2020  21:12               836 rvm.py
03.08.2020  20:57               412 sefr.py
03.08.2020  21:09             1'128 svm.py
03.08.2020  21:00             2'508 utils.py
09.08.2020  15:51             2'094 wifiindoorpositioning.py
08.08.2020  17:43               211 __init__.py
25.08.2020  20:41    <DIR>          __pycache__
              13 Datei(en),         11'597 Bytes
               3 Verzeichnis(se), 160'008'171'520 Bytes frei

probably this can give an indication where to try to solve the issue.

Thank you a lot for helping me!

Best, Adrian

**Comment by eloquentarduino** [comment]
Try

```bash
pip uninstall micromlgen
pip install git+https://github.com/eloquentarduino/micromlgen.git
```

And check that a `template` folder is present in the `micromlgen` folder.

**Comment by AdrianTschannen** [comment]
I am so sad: Unfortunately this did not work:

C:\Users\adria\PycharmProjects\IoT_localization>pip install https://github.com/eloquentarduino/micromlgen.git
Collecting https://github.com/eloquentarduino/micromlgen.git
  Downloading https://github.com/eloquentarduino/micromlgen.git
     | 120 kB 547 kB/s
  ERROR: Cannot unpack file C:\Users\adria\AppData\Local\Temp\pip-unpack-64sv0zv1\micromlgen.git (downloaded from C:\Users\adria\AppData\Local\Temp\pip-req-build-w5feig
3f, content-type: text/html; charset=utf-8); cannot detect archive format
ERROR: Cannot determine archive format of C:\Users\adria\AppData\Local\Temp\pip-req-build-w5feig3f

**Comment by eloquentarduino** [comment]
That's not what I wrote.

```
pip uninstall micromlgen
pip install git+https://github.com/eloquentarduino/micromlgen.git
```

There's a `git+` before the Github repository url.

**Comment by AdrianTschannen** [comment]
correct.
sorry, I put the wrong part of the console in the prior mail. It doesn't work unfortunately:

C:\Users\adria\PycharmProjects\IoT_localization>pip install git+https://github.com/eloquentarduino/micromlgen.git
Collecting git+https://github.com/eloquentarduino/micromlgen.git
  Cloning https://github.com/eloquentarduino/micromlgen.git to c:\users\adria\appdata\local\temp\pip-req-build-hwijbigj
  ERROR: Error [WinError 2] Das System kann die angegebene Datei nicht finden while executing command git clone -q https://github.com/eloquentarduino/micromlgen.git 'C:
\Users\adria\AppData\Local\Temp\pip-req-build-hwijbigj'
ERROR: Cannot find command 'git' - do you have 'git' installed and in your PATH?

**Comment by eloquentarduino** [comment]
1. go to [https://github.com/eloquentarduino/micromlgen](https://github.com/eloquentarduino/micromlgen)
 2. download as Zip (click on the "Code" green button)
 3. copy the `templates` folder inside the `micromlgen` folder to `C:\Users\adria\AppData\Local\Programs\Python\Python37-32\lib\site-packages\micromlgen\`

Does it work now?

**Comment by AdrianTschannen** [comment]
You are e hero! Yes, it works! Thanks a lot for your effort and time.
No I am extremely curious if the generated code works in my arduino!
Merci! Adrian

**Comment by eloquentarduino** [comment]
Here to help :)
