### ISSUE TITLE
error while generating c code

### ISSUE THREAD

**Issue by ruthvikb14** [eloquentarduino/EloquentMicroML#4]
Hi there,

This error keeps displaying while generating C code

TemplateNotFound                          Traceback (most recent call last)
<ipython-input-14-5a8cb77eccf9> in <module>
      1 ocs = OneClassSVM(kernel='rbf', nu=0.5, gamma=0.1)
      2 ocs.fit(df)
----> 3 print(port(ocs))

\lib\site-packages\jinja2\loaders.py in get_source(self, environment, template)
    195 
    196             return contents, filename, uptodate
--> 197         raise TemplateNotFound(template)
    198 
    199     def list_templates(self):

TemplateNotFound: svm/svm.jinja

Could you help me?

**Comment by eloquentarduino** [comment]
If not already, install the latest version of the micromlgen package.

```bash
pip install --upgrade micromlgen
```

If stil having the problem, download the micromlgen package as zip from Github ([link here](https://github.com/eloquentarduino/micromlgen/archive/master.zip)) and extract the `micromlgen-master` folder to your project, renaming it to `micromlgen`.

Remember to uninstall the package from pip.

```bash
pip uninstall micromlgen
```

Now it should work.

**Comment by ruthvikb14** [comment]
I have tried the same thing yesterday and it's working fine. Thank you for your time
